name: 2020-day-08
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '2020/day-08/test.sh'
      - '2020/day-08/io/**'
      - '2020/day-08/solutions/**'

  pull_request:
    branches:
      - main
    paths:
      - '2020/day-08/test.sh'
      - '2020/day-08/io/**'
      - '2020/day-08/solutions/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 
    steps:
      - uses: actions/checkout@v2
      - name: make versions
        run: make versions
      - name: make test
        run: make 2020.day-08
