name: day-16
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'days/day-16/**'
    paths-ignore:
      - 'days/day-16/README.md'

  pull_request:
    branches:
      - main
    paths:
      - 'days/day-16/**'
    paths-ignore:
      - 'days/day-16/README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: 
    steps:
      - uses: actions/checkout@v2
      - name: make versions
        run: make versions
      - name: make test
        run: make test DAY=day-16
