name: days/day-00-example
on:
  push:
    paths:
      - 'days/day-00-example/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jonasjso/adventofcode2020:latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: make test DAY=day-00-example
