name: day-00-example
on:
  push:
    branches:
      - main
    paths:
      - 'days/day-00-example/**'
      - 'lang/**'
      - 'Makefile'
  pull_request:
    branches:
      - main
    paths:
      - 'days/day-00-example/**'
      - 'lang/**'
      - 'Makefile'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "jonasjso/adventofcode2020:2020-12-18-with-zig-v0.7.1"
    steps:
      - uses: actions/checkout@v2
      - name: make versions
        run: make versions
      - name: make test
        run: make test DAY=day-00-example
