name: day-20
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'days/day-20/**'
  pull_request:
    branches:
      - main
    paths:
      - 'days/day-20/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "jonasjso/adventofcode2020:2020-12-04-with-polyc-fix"
    steps:
      - uses: actions/checkout@v2
      - name: make versions
        run: make versions
      - name: make test
        run: make test DAY=day-20
