name: day-11
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'days/day-11/**'
    paths-ignore:
      - 'days/day-11/README.md'

  pull_request:
    branches:
      - main
    paths:
      - 'days/day-11/**'
    paths-ignore:
      - 'days/day-11/README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "jonasjso/adventofcode2020:2020-12-07-with-deno"
    steps:
      - uses: actions/checkout@v2
      - name: make versions
        run: make versions
      - name: make test
        run: make test DAY=day-11
