name: day-13
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'days/day-13/**'
  pull_request:
    branches:
      - main
    paths:
      - 'days/day-13/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "jonasjso/adventofcode2020:2020-12-07-with-deno"
    steps:
      - uses: actions/checkout@v2
      - name: make versions
        run: make versions
      - name: make test
        run: make test DAY=day-13
