name: days/day-14
on:
  push:
    paths:
      - 'days/day-14/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jonasjso/adventofcode2020:latest
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test DAY=day-14
