name: day-01
on:
  workflow_dispatch:
  push:
    paths:
      - 'days/day-01/**'
  pull_request:
    branches:
      - main
    paths:
      - 'days/day-01/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "jonasjso/adventofcode2020:2020-12-01-with-ruby"
    steps:
      - uses: actions/checkout@v2
      - name: make versions
        run: make versions
      - name: make test
        run: make test DAY=day-01
