name: day-03
on:
  push:
    paths:
      - 'day-03/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: jonasjso/adventofcode2020
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test DAY=day-03
