name: day-24
on:
  push:
    paths:
      - 'day-24/**'

jobs:
test:
    runs-on: ubuntu-latest
    container:
    image: jonasjso/adventofcode2020
    steps:
      - uses: actions/checkout@v2
      - name: make test
        run: make test DAY=day-24
