name: day-04
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'days/day-04/test.sh'
      - 'days/day-04/io/**'
      - 'days/day-04/solutions/**'

  pull_request:
    branches:
      - main
    paths:
      - 'days/day-04/test.sh'
      - 'days/day-04/io/**'
      - 'days/day-04/solutions/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "jonasjso/adventofcode2020:2020-12-18-with-zig-v0.7.1"
    steps:
      - uses: actions/checkout@v2
      - name: make versions
        run: make versions
      - name: make test
        run: make test DAY=day-04
