name: day-example
on:
  push:
    branches:
      - main
    paths:
      - 'day-example/**'
      - 'lang/**'
      - 'Makefile'
  pull_request:
    branches:
      - main
    paths:
      - 'day-example/**'
      - 'lang/**'
      - 'Makefile'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "jonasjso/adventofcode2020:2020-12-18-with-zig-v0.7.1"
    steps:
      - uses: actions/checkout@v2
      - name: running ./scripts/print-versions.sh
        run: ./scripts/print-versions.sh
      - name: running ./day-example/test.sh
        run: ./day-example/test.sh

