name: examples
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/examples.yaml'
      - 'lang/**'
      - 'lib/**'
      - 'examples/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/examples.yaml'
      - 'lang/**'
      - 'lib/**'
      - 'examples/**'
  workflow_dispatch:

jobs:
  examples:
    runs-on: ubuntu-latest
    container:
      image: jonasjso/adventofcode2020:2021-12-04-with-kotlin-1.5.32-take3
    steps:
      - uses: actions/checkout@v2
      - name: running ./scripts/print-versions.sh
        run: ./scripts/print-versions.sh
      - name: running ./examples/test.sh
        run: ./examples/test.sh

